/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
  // Apply the java-library plugin for API and implementation separation.
  `java-library`
  id("io.freefair.lombok") version ("6.5.1")
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  // Use JUnit Jupiter for testing.
  testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")

  // This dependency is exported to consumers, that is to say found on their compile classpath.
  // https://mvnrepository.com/artifact/jakarta.persistence/jakarta.persistence-api
  api("jakarta.persistence:jakarta.persistence-api:3.1.0")

  // This dependency is used internally, and not exposed to consumers on their own compile classpath.

  // https://mvnrepository.com/artifact/org.springframework/spring-jdbc
  implementation("org.springframework:spring-jdbc:5.3.24")
//  implementation("mysql:mysql-connector-java:8.0.17")
  // https://mvnrepository.com/artifact/com.zaxxer/HikariCP
  implementation("com.zaxxer:HikariCP:5.0.1")

  compileOnly("org.projectlombok:lombok:1.18.24")
  // https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
  testImplementation("ch.qos.logback:logback-classic:1.4.5")

  testImplementation("com.h2database:h2:2.1.214")
}

tasks.named<Test>("test") {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()
}
